### ISSUE TITLE
IndexError: argmin(): Expected reduction dim to be specified for input.numel() == 0.

### ISSUE THREAD

**Issue by tyutlk** [dvlab-research/VoxelNeXt#28]
Traceback (most recent call last):                          
  File "train.py", line 231, in <module>
    main()
  File "train.py", line 200, in main
    cfg=cfg
  File "/mnt/cache/liukai3/dev0510/OpenPCDet/tools/train_utils/train_utils.py", line 194, in train_model
    use_amp=use_amp
  File "/mnt/cache/liukai3/dev0510/OpenPCDet/tools/train_utils/train_utils.py", line 56, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "../pcdet/models/__init__.py", line 44, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/mnt/cache/liukai3/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/cache/liukai3/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/mnt/cache/liukai3/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/mnt/cache/liukai3/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "../pcdet/models/detectors/voxelnext.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/mnt/cache/liukai3/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "../pcdet/models/dense_heads/voxelnext_head.py", line 535, in forward
    data_dict['gt_boxes'], num_voxels, spatial_indices, spatial_shape
  File "../pcdet/models/dense_heads/voxelnext_head.py", line 160, in assign_targets
    min_radius=target_assigner_cfg.MIN_RADIUS,
  File "../pcdet/models/dense_heads/voxelnext_head.py", line 225, in assign_target_of_single_head
    inds[k] = distance.argmin()
IndexError: argmin(): Expected reduction dim to be specified for input.numel() == 0.

Hi,thanks for your great work,when training my own dataset using my own data augmentation,the ERROR always occurs randomly after training serveral epochs , so i wonder how it works and whether made by my own dataset and my own data augmentation.

**Comment by yukang2017** [comment]
Hi, I think this might be caused from that the voxel features in some frames are very few. I think you can add a line of `continue` to skip the computation `if distance.numel() == 0`.
